### ISSUE TITLE
Permission Error and Attribute Error during usage

### ISSUE THREAD

**Issue by Meghdeep** [jophy/fasttld#3]
**Permission Error:**

    import fasttld
  File "/usr/local/lib/python3.5/dist-packages/fasttld/__init__.py", line 12, in <module>
    from fasttld.FastTLDExtract import FastTLDExtract
  File "/usr/local/lib/python3.5/dist-packages/fasttld/FastTLDExtract.py", line 11, in <module>
    from fasttld.psl import getPublicSuffixList
  File "/usr/local/lib/python3.5/dist-packages/fasttld/psl.py", line 99, in <module>
    auto_update()
  File "/usr/local/lib/python3.5/dist-packages/fasttld/psl.py", line 97, in auto_update
    update(show_output=False)
  File "/usr/local/lib/python3.5/dist-packages/fasttld/psl.py", line 78, in update
    raise Exception('[+]PSL UPDATES Error:' + str(e))
Exception: [+]PSL UPDATES Error:[Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/fasttld/public_suffix_list.dat'

**Attribute Error:**

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fasttld/psl.py", line 69, in update
    downfile = urllib.URLopener()
AttributeError: module 'urllib' has no attribute 'URLopener'

**Comment by jophy** [comment]
Please provide me with more details, OS version, User permission.

Please check you can access /usr/local/lib/python3.5/dist-packages/fasttld/public_suffix_list.dat

Or you could setup manually

`>>> from fasttld import FastTLDExtract`
`>>> FastTLDExtract(file_path='/path/to/psl/file').extract('domain', subdomain=False)`

Attribute Error, maybe cause of your local urllib package conflict . Please create a py env.

Thank you.
